# Generated by Django 5.1.15 on 2026-07-17 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='filename')),
                ('source', models.CharField(max_length=255, verbose_name='source')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='duration')),
                ('success', models.BooleanField(default=False, verbose_name='success')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('processed_documents', models.PositiveIntegerField(default=0, verbose_name='processed documents')),
                ('failed_documents', models.PositiveIntegerField(default=0, verbose_name='failed documents')),
                ('warning_count', models.PositiveIntegerField(default=0, verbose_name='warning count')),
                ('execution_log', models.TextField(blank=True, verbose_name='execution log')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finished at')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL, verbose_name='imported by')),
            ],
            options={
                'verbose_name': 'import job',
                'verbose_name_plural': 'import jobs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['success', 'started_at'], name='imports_imp_success_2221a2_idx'), models.Index(fields=['imported_by', 'started_at'], name='imports_imp_importe_79fd69_idx')],
            },
        ),
    ]
