# Generated by Django 5.1.15 on 2026-07-17 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('prefix', models.CharField(max_length=20, unique=True, verbose_name='prefix')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('yearly_reset', models.BooleanField(default=True, verbose_name='yearly reset')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'document type',
                'verbose_name_plural': 'document types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='year')),
                ('current_number', models.PositiveIntegerField(default=0, verbose_name='current number')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='documents.documenttype', verbose_name='document type')),
            ],
            options={
                'verbose_name': 'document counter',
                'verbose_name_plural': 'document counters',
                'ordering': ['document_type__code', 'year'],
                'constraints': [models.UniqueConstraint(fields=('document_type', 'year'), name='unique_document_counter_per_year')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, unique=True, verbose_name='number')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('paperless_id', models.IntegerField(blank=True, null=True, verbose_name='paperless id')),
                ('original_filename', models.CharField(max_length=255, verbose_name='original filename')),
                ('stored_filename', models.CharField(max_length=255, verbose_name='stored filename')),
                ('document_date', models.DateField(verbose_name='document date')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='amount')),
                ('currency', models.CharField(default='MAD', max_length=3, verbose_name='currency')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('sha256', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='sha256')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='imported at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IMPORTED', 'Imported'), ('FAILED', 'Failed'), ('ARCHIVED', 'Archived')], default='NEW', max_length=20, verbose_name='status')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documenttype', verbose_name='document type')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='documents_d_company_f009e1_idx'), models.Index(fields=['document_type', 'status'], name='documents_d_documen_174e8d_idx'), models.Index(fields=['document_date'], name='documents_d_documen_0eb394_idx'), models.Index(fields=['status', 'created_at'], name='documents_d_status_64808e_idx')],
            },
        ),
    ]
